### ISSUE TITLE
SPI communication not working. Set chip select pin as OUTPUT

### ISSUE THREAD

**Issue by ghost** [Ell-i/ELL-i-KiCAD-Boards#5]
I'm currently using an [Adafruit Feather 32u4](https://learn.adafruit.com/adafruit-feather-32u4-basic-proto/pinouts) with the TYSY01 sensor and I was unable retrieve data over the SPI protocol. I'm able to correctly communicate and read data from the TYSY01 sensor over I2C, however, I'm receiving incorrect data over SPI.

I'm using version 1.8.10 of the Arduino IDE with the code provided by this [Instructables guide](https://www.instructables.com/id/How-to-Measure-Temperature-Very-Accurately-With-an/). My code is as follows:
```
#include "Tsys01.h"

#define chipSelectPin 18
#define powerPin 20
#define protocolPin 19

Tsys01 sensor;
float temperature = 0.0;

void setup(void)
{
  while(!Serial);
  Serial.begin(9600);
  Serial.println("Starting program.");
  sensor = Tsys01(TSYS01_SPI, powerPin, chipSelectPin, protocolPin);
}

void loop(void)
{
    sensor.startAdc();

    //ADC takes 9.22 ms.
    delay(10);
    temperature = sensor.readTemperature();
 
    Serial.print("Temperature is ");
    Serial.println(temperature);  
}
```

**Comment by mauriandres** [comment]
It turns out that when using the SPI communication, it is important to define the CS (chip select) pins as output, so the micro-controller can manage the CS lines accordingly. As a safety measure I also drive CS line high just to avoid any floating logic.

I added the following two lines to the setup() section of my sketch:
```
pinMode(chipSelect1, OUTPUT);
digitalWrite(chipSelect1, HIGH);
```

This solved my problem. Thanks @ojousima for your help.

**Comment by ghost** [comment]
It turns out that when using the SPI communication, it is important to define the CS (chip select) pins as output, so the micro-controller can manage the CS lines accordingly. As a safety measure I also drive CS line high just to avoid any floating logic.

I added the following two lines to the setup() section of my sketch:
```
pinMode(chipSelect1, OUTPUT);
digitalWrite(chipSelect1, HIGH);
```

This solved my problem. Thanks @ojousima for your help.

**Comment by ojousima** [comment]
I'll leave this as an open issue for other's knowledge until the example code is fixed. 
Thanks for debugging.

**Comment by Apocalyt** [comment]
Maybe we could configure the pin as output when Tsys01 is constructed using this constructor with SPI Tsys01(TSYS01_SPI, powerPin, chipSelectPin, protocolPin). This should allow example code to work as is. It is quite unlikely that the user wants to simultaneously use it as a input by manually switching the pin mode and in that case user can switch the pin mode back to input anyway.

**Comment by ojousima** [comment]
>Maybe we could configure the pin as output when Tsys01 is constructed using this constructor with SPI Tsys01(TSYS01_SPI, powerPin, chipSelectPin, protocolPin). This should allow example code to work as is. It is quite unlikely that the user wants to simultaneously use it as a input by manually switching the pin mode and in that case user can switch the pin mode back to input anyway.

Sounds good to me, @Apocalyt will you do that?

**Comment by Apocalyt** [comment]
Yes I can do that. Just need to rebuild my test setup, since I have not been using this board in some time.

Maybe I could also test the library with platformio, since I have been using that recently and it likely isn't too much hassle.

**Comment by ojousima** [comment]
Ok, thanks

**Comment by Apocalyt** [comment]
Seems that the issue only happen when not using the default CS pin on pro mini(pin 10), which is probably why it wasn't found before.
